kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "workshop-deployer.name" . }}-namespaces-clusterrole
  labels:
    {{- include "workshop-deployer.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "workshop-deployer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "workshop-deployer.name" . }}-namespaces-clusterrole