kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "workshop-deployer.name" . }}-namespaces-clusterrole
  labels:
    {{- include "workshop-deployer.labels" . | nindent 4 }}
rules:
  - verbs:
      - get
      - create
      - update
      - list
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - create
      - update
    apiGroups:
      - project.openshift.io
    resources:
      - projectrequests
  - verbs:
      - get
      - list
    apiGroups:
      - project.openshift.io
    resources:
      - projects
  - verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles