kind: Secret
apiVersion: v1
metadata:
  name: {{ include "workshop-deployer.name" . }}-proxy
  labels:
    {{- include "workshop-deployer.labels" . | nindent 4 }}
data:
  session_secret: QzAyN3FFV2dSUHMxRjhSdnFRdWxOeEZtN2djaDNlWDdtek9uNG91eGI1Wg==
type: Opaque